server:
    port: 8085
eureka: #tells about the Eureka server details and its refresh time
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: https://eureka-fbba30ba-a0d7-4a96-80e9-f9b36ec1b6a8.cfapps.io
management:
  endpoints:
    web:
      exposure:
        include:
        - helath
        - refresh
        - bus-refresh
        - bus-env
default:
   item:
       id: 1001
       name: dev item
       desc: dev desc
       price: 0.0
