server:
    port: 8084

management:
    security:
        enabled: false
security:
    basic:
        enabled: false
default:
   item:
       id: 1001
       name: default item
       desc: default desc
       price: 0.0
