server:
    port: 8085

management:
    security:
        enabled: false
security:
    basic:
        enabled: false
default:
   item:
       id: 1001
       name: qa item
       desc: qa desc
       price: 0.0
