server:
    port: 8087
eureka: #tells about the Eureka server details and its refresh time
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
        - helath
        - refresh
        - bus-refresh
        - bus-env
default:
   item:
       id: 1001
       name: xyz item
       desc: qa desc
       price: 0.0
