#jdbc uri jdbc:h2:mem:testdb
server:
    port: 8084
eureka: #tells about the Eureka server details and its refresh time
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
default:
   item:
       id: 1001
       name: dev item
       desc: dev desc
       price: 0.0
