server:
    port: 8087

management:
    security:
        enabled: false
security:
    basic:
        enabled: false
default:
   item:
       id: 1001
       name: dev item
       desc: dev desc
       price: 0.0
